apiVersion: v1
kind: Service
metadata:
  name: fastapi-chirpstack-service
  namespace: testing
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi-chirpstack
